drop table IntegerValue;
drop table FractionValue;
drop table StringValue;
drop table DateValue;
drop table TimestampValue;
drop table TextValue;
drop table Lnk;
drop table Lnk3;

alter table Association drop constraint AssPK;
alter table Association3 drop constraint Ass3PK;
drop table Obj;
drop sequence SObj;
drop sequence SLnk;
drop sequence SLnk3;

drop table DeletedObjects;

alter table DeletedObjects_Old rename to DeletedObjects;
alter table DeletedObjects add constraint FDeletedObjectsInstanceOf foreign key (instanceOf) references Cls(id);
create unique index DltdObjInx on DeletedObjects (id, instanceOf);
drop view CmmndExctr;
alter table CmmndExctr_Old rename to CmmndExctr;
drop view Subj;
alter table Subj_Old rename to Subj;
drop view AbsKstnArt;
alter table AbsKstnArt_Old rename to AbsKstnArt;
drop view Trnsktn;
alter table Trnsktn_Old rename to Trnsktn;
drop view ErzgTrnsktnCMD;
alter table ErzgTrnsktnCMD_Old rename to ErzgTrnsktnCMD;
drop view FndKntCMD;
alter table FndKntCMD_Old rename to FndKntCMD;
drop view TrnsFcdTrnsktns;
alter table TrnsFcdTrnsktns_Old rename to TrnsFcdTrnsktns;
drop view Srvr;
alter table Srvr_Old rename to Srvr;
drop view Trnsfr;
alter table Trnsfr_Old rename to Trnsfr;
drop view ErzgKntCMD;
alter table ErzgKntCMD_Old rename to ErzgKntCMD;
drop view BchKntCMD;
alter table BchKntCMD_Old rename to BchKntCMD;
drop view ArtnMngr;
alter table ArtnMngr_Old rename to ArtnMngr;
drop view CmmndCrdntr;
alter table CmmndCrdntr_Old rename to CmmndCrdntr;
drop view CmmnDt;
alter table CmmnDt_Old rename to CmmnDt;
drop view Knt;
alter table Knt_Old rename to Knt;
drop view KntFcd;
alter table KntFcd_Old rename to KntFcd;
drop view TrnsFcd;
alter table TrnsFcd_Old rename to TrnsFcd;
drop view CmmndExctrCommands;
alter table CmmndExctrCommands_Old rename to CmmndExctrCommands;
drop view SubjObs;
alter table SubjObs_Old rename to SubjObs;
drop view TrnsktnTrnsfrs;
alter table TrnsktnTrnsfrs_Old rename to TrnsktnTrnsfrs;
drop view TrnsFcdTrnsktnsObs;
alter table TrnsFcdTrnsktnsObs_Old rename to TrnsFcdTrnsktnsObs;
drop view ArtnMngrArtn;
alter table ArtnMngrArtn_Old rename to ArtnMngrArtn;
drop view CmmndCrdntrExctr;
alter table CmmndCrdntrExctr_Old rename to CmmndCrdntrExctr;
drop view KntFcdKntn;
alter table KntFcdKntn_Old rename to KntFcdKntn;
